	pipeline {
    agent any

    tools {
        maven 'Maven-3.8.6'
        jdk 'JDK-11'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git url: 'https://github.com/pankajbhavate/inventory.git', branch: 'master'
            }
        }

        stage('Build & Run Tests') {
            steps {
                sh 'mvn clean test'
            }
        }

        stage('Publish Reports') {
            steps {
                publishHTML([allowMissing: false,
                             alwaysLinkToLastBuild: true,
                             keepAll: true,
                             reportDir: 'target/surefire-reports',
                             reportFiles: 'index.html',
                             reportName: 'TestNG HTML Report'])
            }
        }
    }
}
